name: pull-request-to-master

on:
  pull_request:
    branches: [ main ]

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test and publish coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: go test -coverprofile=gocov.out -v ./... 
        coverageLocations: ${{github.workspace}}/gocov.out:gocov
        prefix: github.com/heltonuema/fullcycle-desafio-go

    